# Generated by Django 3.2.4 on 2021-09-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('coursepic', models.ImageField(default='', upload_to='static/ourcourses/')),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='cdescription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cpic',
            field=models.ImageField(default='', upload_to='static/coure'),
        ),
    ]
